extends:
  - 'airbnb-base'
env:
   node: true
plugins:
  - 'eslint-plugin-import'
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
